### ISSUE TITLE
Suggestion: Resources outside of src

### ISSUE THREAD

**Issue by dereuromark** [matthiasnoback/layers-ports-and-adapters-workshop#47]
Having resource files inside autoloaded src/ is actually an anti pattern
See also https://github.com/php-pds/skeleton
They should be under top level /resources etc.

It also makes it easier to work with the autoloaded path, as it now only contains valid autoloadable PHP files it is also faster to autoload.

For the course of the workshops it also makes it a bit more easy to work with the classes in src/.
I was bothered by that folder being there :)

**Comment by matthiasnoback** [comment]
Thanks for your suggestion, and making the effort to submit an issue for it! I didn't know about that package skeleton, seems really useful.

I had actually decided to put those files in src because it forces people to think about where do these files belong. Templates aren't necessarily resources after all, they could be plain old classes too. So, I'll keep it like this.
